### ISSUE TITLE
Terminate a long-running script

### ISSUE THREAD

**Issue by stkb** [fknop/vscode-npm#1]
Hi, thanks for the plugin!

The one thing I miss at the moment (unless I missed it), is the ability to terminate a long-running script (eg a watch script). Like vscode's own "Terminate Running Task" command.

**Comment by fknop** [comment]
Hi @stkb,

I'm glad you like it. I'll see what I can do about that this week-end !

Thanks for the suggestion.

**Comment by fknop** [comment]
Hi,

I published `3.0.0`. You can try it and tell me if you find a bug. I only tested it on Windows. I don't have Unix right now.

I used the npm module `tree-kill`. 

Windows doesn't have feedback yet. But it should work.

**Comment by stkb** [comment]
Thanks :+1: It works great! (I'm only on Windows too)

You said it doesn't have feedback yet; not sure if this is what you meant but it would be great if you could just add a line to the npm output pane to say the script's been terminated.

**Comment by fknop** [comment]
Yes, that is what I meant, I'll do that soon. Should take 5 minutes :)

**Comment by stkb** [comment]
Great! will close this now

**Comment by fknop** [comment]
I added a little feedback when we try to terminate a process. 
But for now, on Windows, I don't know how to make the difference between a killed process and a code 1 exit. The signal is null because `SIGTERM` doesn't exist on windows.

**Comment by stkb** [comment]
No, there seems to be no way to tell on Windows. 

What I would have done maybe is add an extra flag, like `wasKilled`, to `ChildCommand`.
Then set this flag in the `terminate` function, and then check for its presence in the onExit event of the child process.

**Comment by fknop** [comment]
Yeah I thought about it too. I guess I'll do that then ! :)
