### ISSUE TITLE
shortcut for npm start and npm test

### ISSUE THREAD

**Issue by Guria** [fknop/vscode-npm#3]
Would be great to have `npm start` and `npm test` commands on top level, so it could be run by typing `> npm start` in command pallette.

**Comment by fknop** [comment]
If I understand correctly, you want to have `npm start` and `npm test` directly instead of doing `npm run` then your command ?

**Comment by Guria** [comment]
yes, you are right

**Comment by fknop** [comment]
Ok, it should not be too hard, I'll try to do this tomorrow.

**Comment by fknop** [comment]
Hey!

Sorry for the delay, I finally got the time to do it, it's published !
