### ISSUE TITLE
npm start end with "Successfully killed process" before runing

### ISSUE THREAD

**Issue by PhoneixS** [fknop/vscode-npm#8]
I can't start any angular2 project with the command `npm start`, it ends when it comes to 65%.

This are the steps:
1. I created a new project with `ng new willcrash` from my terminal.
2. Then I opened the folder "willcrash" with Visual Code.
3. Ctrl+Shift+P and type npm start.
4. It started building modules when "Successfully killed process" appears in the output. And a `npm-debug.log.2595600053` file is created (but it's empty).

I have:
- angular-cli: 1.0.0-beta.18
- node: 6.2.2
- os: Ubuntu 16.04
- Visual Studio Code: 1.6.1

If I run the npm command directly from console it runs without problem.

This is part of the output:

`npm run start

> willcrash@0.0.0 start /home/jabellota/willcrash
> ng serve

*\* NG Live Development Serv 10% building modules 0/1 modules 1

active multi main
10% building modules 1/1

... 

65% building modules 562/603 modules 41 active ...form-browser/src/facade/collection.js
65% building modules 562/604 modules 42 active .../node_modules/rxjs/util/isFunction.js
65% building modules 562/605 modules 43 active ...llcrash/node_modules/rxjs/Observer.js
Successfully killed process

--------------------`

**Comment by fknop** [comment]
I used a little bit `angular-cli`. It's kind of buggy sometimes (still in beta). It's probably not working properly with VSCode and/or exec API.

I'm closing because I don't think it's coming from the plugin itself.

**Comment by PhoneixS** [comment]
But if I run the command in the terminal it run without flaw, included the VSCode integrated terminal. I only use angular-cli to init the folder with start files and, from my point of view, it's made  correctly.

Moreover, it's really strange that it ended in the middle of the process with a "Successfully killed process" that is show when you get a SIGTERM signal (as if someone try to kill it).

**Comment by Tsmith18256** [comment]
I get this as well with an Ionic application. It just randomly quits in the middle of our gulp pipeline with the "Successfully killed process" message.

**Comment by fknop** [comment]
It's weird because as you can see here: https://github.com/fknop/vscode-npm/blob/master/src/run-command.ts#L41, it only displays that message if the process exits in the first place.

The message was created just to have a human friendly message when the child is killed.

**Comment by Tsmith18256** [comment]
Hmmm... something must be causing the processes to exit in VS Code then. Just like with @PhoneixS, I can run the same command over and over and it will always work, but refuses to work a large chunk of the time from within VS Code.

**Comment by Tsmith18256** [comment]
@fknop Just thought about this some more. I think what's happening is it's getting the signal from the first process ending and not continuing to the next one if you have `&&` in your NPM script.

Edit: Tried it with `npm-run-all` and it's the same thing. The command I am trying is `gulp && ionic run android`. Every time it seems to exit after Gulp finishes.

**Comment by otakustay** [comment]
I encountered this issue too, it does not seems a problem with the `&&` in npm script like @Tsmith18256 said, my npm script just call a bash and it is killed after about 50s, could it be a timeout problem?

**Comment by keerthivasan-r** [comment]
This is something that needs to be looked how __vscode-npm__ plugin does the work. when i issue __npm start__ in the integrated terminal, it just works flawlessly :+1:
